# Generated by Django 5.2.7 on 2025-11-02 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('category', models.CharField(choices=[('BURGER', '汉堡'), ('SNACK', '小食'), ('DRINK', '饮料'), ('COMBO', '套餐')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='产品图片')),
                ('is_available', models.BooleanField(default=True, verbose_name='是否可用')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
