# Generated by Django 5.2.7 on 2025-10-28 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=20, unique=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('PENDING', '待支付'), ('PAID', '已支付'), ('PREPARING', '制作中'), ('READY', '待取餐'), ('COMPLETED', '已完成'), ('CANCELLED', '已取消')], default='PENDING', max_length=20)),
                ('payment_method', models.CharField(choices=[('CASH', '现金'), ('ALIPAY', '支付宝'), ('WECHAT', '微信支付'), ('CARD', '银行卡')], max_length=20)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('completed_time', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
    ]
