# Generated by Django 5.2.7 on 2025-11-09 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='completed_time',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(db_index=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('CASH', '现金'), ('ALIPAY', '支付宝'), ('WECHAT', '微信支付'), ('CARD', '银行卡')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', '待支付'), ('PAID', '已支付'), ('PREPARING', '制作中'), ('READY', '待取餐'), ('COMPLETED', '已完成'), ('CANCELLED', '已取消')], db_index=True, default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_amount',
            field=models.DecimalField(db_index=True, decimal_places=2, max_digits=10),
        ),
    ]
