# Generated by Django 5.2.7 on 2025-11-09 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_order_completed_time_alter_order_created_at_and_more'),
        ('orderitem', '0001_initial'),
        ('product', '0003_alter_product_category_alter_product_created_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='price',
            field=models.DecimalField(db_index=True, decimal_places=2, max_digits=8, verbose_name='单价'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.PositiveIntegerField(db_index=True, default=1, verbose_name='数量'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['order', 'product'], name='order_item_order_i_ca54a9_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['price', 'quantity'], name='order_item_price_76a97b_idx'),
        ),
    ]
